### ISSUE TITLE
Stops working and sometimes doesn't work on start.

### ISSUE THREAD

**Issue by Tape-Worm** [sw3103/movemouse#66] opened 2024-03-07 18:15 UTC
When I launch the application, the auto resume timer sometimes doesn't start. Furthermore, after some unknown event or time, the auto resume timer stops and the app stops working.  I have confirmed this by viewing the log.  When it works, the auto resume timer shows up in the log, and when it's not, the timer does not output anything.

**Comment by sw3103** [comment] 2024-03-21 17:37
Hi,

Could you please send me the log file along with the times these events occurred?

contact@movemouse.co.uk

Thanks

**Comment by rgagnon24** [comment] 2024-03-22 08:12
I have this same issue.  Where would the log file be found?

**Comment by sw3103** [comment] 2024-03-22 16:56
> ![Capture](https://private-user-images.githubusercontent.com/546197/315936813-d8bfd991-82d4-4268-945e-e37750a17c46.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjY4ODEsIm5iZiI6MTcxMTEyNjU4MSwicGF0aCI6Ii81NDYxOTcvMzE1OTM2ODEzLWQ4YmZkOTkxLTgyZDQtNDI2OC05NDVlLWUzNzc1MGExN2M0Ni5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNjU2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWIyN2JmOTNjOTkyODdlMmNlNTRiYmMyZjhhOWIyMjg4ZDIyNGY2NDYzYTJkYjlmYjJjODY1Nzc3OWRjOTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xmZg5r5oZeEB_1fX4q-ExE567cd2w5T65Iq01_Rd_Sk) I have this same issue. I noticed it seems you have to click on the mouse's face once after the program starts to get the timers to engage, but it does just stop working after some random amount of time.
> 
> Where would the log file be found? (Using v4.16.3)
> 
> Also... 80MB Memory usage seems excessive for what this does

https://github.com/sw3103/movemouse/wiki/Troubleshooting

**Comment by Tape-Worm** [comment] 2024-03-23 02:08
When it happens again, I'll get the log for you. It seems random, so it can work fine for hours or days and then die.

**Comment by Tape-Worm** [comment] 2024-04-02 15:26
Finally!  I have your log, I've uploaded it to my website, you can grab it from this link:
https://www.tape-worm.net/public/MoveMouseLog.zip

It stopped working around 9-9:30 AM (MST) this morning (2024-04-02).

**Comment by sw3103** [comment] 2024-04-17 12:53
Hi Mike,

Thanks for the logs. I have been away for a couple of weeks hence the lack of response.

I'll have a look soon and hopefully see if I can spot the issue.

**Comment by Tape-Worm** [comment] 2024-04-17 17:33
> Hi Mike,
> 
> Thanks for the logs. I have been away for a couple of weeks hence the lack of response.
> 
> I'll have a look soon and hopefully see if I can spot the issue.

No worries or rush. It's probably just all in my head, but adding blackout times seems to have helped a bit (I still get the problem, just not as frequently).

**Comment by sw3103** [comment] 2024-04-24 19:39
The logs haven't revealed a great deal, but I have noticed a small anomaly where the _autoPauseTimer was allowed to go over the specified 5 seconds, and was still running whilst Move Mouse was performing the actions. I am not sure at this moment whether this is the cause or a symptom of the issue.

I have left Move Mouse running with your exact configuration on a VM to see if I can reproduce the issue.

Thanks for your patience.

**Comment by sw3103** [comment] 2024-04-30 10:32
It's been running faultlessly for nearly six days now. How long did it normally take for you to see the issue?

**Comment by Tape-Worm** [comment] 2024-05-02 02:13
Sometimes it'd screw up every day, other times it took a week or more.

**Comment by VasaXter** [comment] 2024-05-10 09:13
I have similar issue, MM won't resume the work. When logged, it look like it keeps resseting  the counter.
I had this issue starting like month and something ago, but when I started logging it magically started behaving properly.
With new version it goes like this for whole time. (setting is move each 60s, autopause, sesuem after 90s)
Tried to change various settings, running MM as admin, nothing helps

2024-05-10 11:05:04.076 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:04.327 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:04.578 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:04.828 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:05.079 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:05.330 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:05.580 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:05.830 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:06.081 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:06.331 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:06.582 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:06.832 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:07.083 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:07.333 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:07.584 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:07.834 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:08.084 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0160000
2024-05-10 11:05:08.335 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0160000
2024-05-10 11:05:08.585 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0160000
2024-05-10 11:05:08.836 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0160000
2024-05-10 11:05:09.086 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:09.337 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:09.588 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0160000
2024-05-10 11:05:09.839 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:10.090 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:10.340 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0160000
2024-05-10 11:05:10.590 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:10.841 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:11.092 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:11.343 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:11.594 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:11.846 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:12.097 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:12.347 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:12.598 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:12.848 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:13.099 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:13.349 [DBG]   _autoResumeTimer_Elapsed        00:00:00
2024-05-10 11:05:13.600 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0150000
2024-05-10 11:05:13.850 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0150000
2024-05-10 11:05:14.101 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0150000
2024-05-10 11:05:14.351 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0150000
2024-05-10 11:05:14.601 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0150000
2024-05-10 11:05:14.852 [DBG]   _autoResumeTimer_Elapsed        00:00:00.0150000

**Comment by sw3103** [comment] 2024-05-11 07:35
> I have similar issue, MM won't resume the work. When logged, it look like it keeps resseting the counter. I had this issue starting like month and something ago, but when I started logging it magically started behaving properly. With new version it goes like this for whole time. (setting is move each 60s, autopause, sesuem after 90s) Tried to change various settings, running MM as admin, nothing helps
> 
> 2024-05-10 11:05:04.076 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:04.327 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:04.578 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:04.828 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:05.079 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:05.330 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:05.580 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:05.830 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:06.081 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:06.331 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:06.582 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:06.832 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:07.083 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:07.333 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:07.584 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:07.834 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:08.084 [DBG] _autoResumeTimer_Elapsed 00:00:00.0160000 2024-05-10 11:05:08.335 [DBG] _autoResumeTimer_Elapsed 00:00:00.0160000 2024-05-10 11:05:08.585 [DBG] _autoResumeTimer_Elapsed 00:00:00.0160000 2024-05-10 11:05:08.836 [DBG] _autoResumeTimer_Elapsed 00:00:00.0160000 2024-05-10 11:05:09.086 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:09.337 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:09.588 [DBG] _autoResumeTimer_Elapsed 00:00:00.0160000 2024-05-10 11:05:09.839 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:10.090 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:10.340 [DBG] _autoResumeTimer_Elapsed 00:00:00.0160000 2024-05-10 11:05:10.590 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:10.841 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:11.092 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:11.343 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:11.594 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:11.846 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:12.097 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:12.347 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:12.598 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:12.848 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:13.099 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:13.349 [DBG] _autoResumeTimer_Elapsed 00:00:00 2024-05-10 11:05:13.600 [DBG] _autoResumeTimer_Elapsed 00:00:00.0150000 2024-05-10 11:05:13.850 [DBG] _autoResumeTimer_Elapsed 00:00:00.0150000 2024-05-10 11:05:14.101 [DBG] _autoResumeTimer_Elapsed 00:00:00.0150000 2024-05-10 11:05:14.351 [DBG] _autoResumeTimer_Elapsed 00:00:00.0150000 2024-05-10 11:05:14.601 [DBG] _autoResumeTimer_Elapsed 00:00:00.0150000 2024-05-10 11:05:14.852 [DBG] _autoResumeTimer_Elapsed 00:00:00.0150000

This is a separate issue. Something on your workstation (unlikely Move Mouse itself) is simulating user activity and resetting the idle time, which will not Move Mouse to automatically resume. I have seen this issue in the past which was due to a bug in some [NVIDIA](https://github.com/sw3103/movemouse/wiki/Troubleshooting#nvidia-software) software.

My advice would be to run the script from the following section of the Troubleshooting guide to help you identify what may be the culprit:

https://github.com/sw3103/movemouse/wiki/Troubleshooting#idle-time

Presumably your idle time will be constantly getting reset. Try closing applications one at a time (look for the background ones running in your system tray), pausing between each one to see if your idle time is allowed to increase.

**Comment by Tape-Worm** [comment] 2024-05-11 19:55
I've updated to the latest version (4.18, I wasn't aware it had been updated). I'll let you know if I run into the same problem.

And I'm a total dumbass. I didn't think to tell you I'm running MouseMove under a Hyper-VM Windows 11 Pro VM. Sorry about that, I really should have mentioned that earlier. Totally slipped my addled old man brain.

**Comment by techtalk722** [comment] 2024-06-07 12:30
Hi.  I'm not sure if my issue is the same thing or not, but the symptom seems to be the same.

This started happening to me on a newly built Win10 VM.  I have used MM for years (thank you, by the way) in other VMs as a way to maintain a presence status in Teams and keep the screen active while I do work in other VMs.  I have previously used it in Win10 and Win11 with no issues.  This time, Windows and MM don't want to work together.  I am using the most current version, 4.18.2.

I have installed it and configured it as I have always used it, using a schedule during work hours with a stealth movement.  I have also tried just leaving it with the default settings, but nothing seems to make it actually move the mouse.  I've even configured actual slow movement (to see the mouse move), but the mouse just never moves.  The screensaver will come on and Teams will revert to an 'away' status.

I have run the troubleshooting PS script and it runs for long periods of time with nothing ever resetting the idle state running in the script, even while MM is running.  While watching the verbose log output, I can see it run every 30 seconds, but again, the mouse doesn't seem to actually move.  Below is a sample from today of what is being posted to my log file every 30 seconds.

If this is the same issue and there's anything I can do or provide, please let me know.  I love this tool.

2024-06-07 14:19:13.790	[INF]	PerformActions	Interval
2024-06-07 14:19:13.790	[INF]	PerformActions	_firstPass = False
2024-06-07 14:19:13.790	[DBG]	BlackoutIsActive	False
2024-06-07 14:19:13.790	[INF]	CurrentState	Executing
2024-06-07 14:19:13.790	[DBG]	OnMouseStateChanged	Executing
2024-06-07 14:19:13.790	[DBG]	_vm_MouseStateChanged	Executing
2024-06-07 14:19:13.792	[DBG]	StopAutoPauseTimer	
2024-06-07 14:19:13.792	[DBG]	Action_PropertyChanged	IntervalExecutionCount
2024-06-07 14:19:13.792	[DBG]	Settings_PropertyChanged	Actions
2024-06-07 14:19:13.792	[DBG]	SaveSettings	C:\Users\Switchkat\AppData\Roaming\Ellanet\Move Mouse\Settings.xml
2024-06-07 14:19:13.793	[DBG]	Settings_PropertyChanged	Actions
2024-06-07 14:19:13.793	[INF]	Execute	MoveMouseCursorAction | Name =  | Distance = 10 | Direction = None | Speed = Normal | Delay = 5 | Trigger = Interval | Repeat = True | RepeatMode = Forever | IntervalThrottle = 1 | IntervalExecutionCount = 45 | InterruptsIdleTime = True
2024-06-07 14:19:13.793	[INF]	Start	
2024-06-07 14:19:13.793	[DBG]	BlackoutIsActive	False
2024-06-07 14:19:13.793	[DBG]	StopAutoResumeTimer	
2024-06-07 14:19:13.793	[INF]	ExecutionTime	14:19:43
2024-06-07 14:19:13.793	[INF]	CurrentState	Running
2024-06-07 14:19:13.793	[DBG]	OnMouseStateChanged	Running
2024-06-07 14:19:13.793	[DBG]	_vm_MouseStateChanged	Running
2024-06-07 14:19:13.803	[DBG]	StopBlackoutTimer	
2024-06-07 14:19:13.803	[DBG]	StartAutoPauseTimer	
2024-06-07 14:19:13.803	[DBG]	StopAutoPauseTimer

**Comment by sw3103** [comment] 2024-10-12 10:56
> I've updated to the latest version (4.18, I wasn't aware it had been updated). I'll let you know if I run into the same problem.
> 
> And I'm a total dumbass. I didn't think to tell you I'm running MouseMove under a Hyper-V Windows 11 Pro VM. Sorry about that, I really should have mentioned that earlier. Totally slipped my addled old man brain.

@Tape-Worm has this issue persisted since running 4.18?

**Comment by Tape-Worm** [comment] 2024-10-13 22:08
Hey, the only times I've had it stop working since 4.18, is when I've logged in after rebooting the host system, or logging out of the guest OS and logging back in. In either case, a simple shut down of the application and restart seems to put it back on the rails. If I remember correctly, prior to 4.18, it would stop working regardless of whether I shut it down/restarted it or not.

I'm expecting this has something to do with the VM under Hyper-V more than anything. In which case, since I seem to have a work around for now, seems to be a rather slim edge case that you shouldn't need to worry about. I don't expect you to set up a full Hyper-V/VM scenario to test this, that's more work than I'd want to put in for sure :) So if you want to close this as an wontfix/edge case, be my guest.

**Closed** 2024-11-02 10:30 UTC
Labels: bug
