### ISSUE TITLE
Tooltip seems to be stuck in top left corner of the screen

### ISSUE THREAD

**Issue by edinmusic** [sw3103/movemouse#52] opened 2023-08-02 15:41 UTC
As shown here (crop of screenshot):

<img width="264" alt="image" src="https://github.com/sw3103/movemouse/assets/1936658/fc24d347-fa78-4507-a217-9343d59f734f">

**Comment by sw3103** [comment] 2023-08-03 15:07
Can you reproduce this issue?

I have seen this before a few times on Windows with various applications where the tooltip persists for icons in the system tray. Normally just re-hovering the mouse over the offending icon will make it disappear.

**Comment by edinmusic** [comment] 2023-08-09 15:17
I can't reproduce it manually. Hovering over app icon does make it disappear. 

It happens without rules, just sometimes for no reason. No other app does it. Only difference between this and other apps is that this looks like custom implementation, and all others use default Windows tooltip implementation.

If it makes any difference, it's on latest Windows 11.

**Comment by sw3103** [comment] 2023-08-10 11:32
The implementation of the tooltip is standard, although it has been given a custom style which should not in any way affect the behaviour.

If you send me an email I can give you a test version without the tooltip styling to see if that makes a difference?

contact@movemouse.co.uk

**Comment by dougbenham** [comment] 2023-08-10 22:06
I have this issue quite a bit as well. I emailed you.

**Comment by edinmusic** [comment] 2023-09-02 16:47
I've used that release for few days and haven't had any issues. 
Btw, tooltip implementation still differs from the default one on Windows 11, just so you know, but works correctly.

<img width="144" alt="image" src="https://github.com/sw3103/movemouse/assets/1936658/f808a943-5c12-4649-b58f-78af5eb5c869">

**Comment by edinmusic** [comment] 2023-09-07 13:28
Managed to catch it in the top left corner again:
<img width="276" alt="image" src="https://github.com/sw3103/movemouse/assets/1936658/18de30c3-009a-4bf0-8c9a-0b1a464ed071">

**Comment by sw3103** [comment] 2023-09-08 08:43
I see on your previous screenshot that the Microsoft Outlook tooltip is translucent, but what about the rest?

The tooltip in the test version I gave you has no styling, and therefore should match the system default, as it does on my Windows 11 workstation.

![image](https://github.com/sw3103/movemouse/assets/29467423/6d76701f-9d02-4a73-baf6-c340400f5154)

**Comment by edinmusic** [comment] 2023-09-09 18:22
Only difference between yours and mine is that I use dark mode, which shouldn't matter.

How does MoveMouse tooltip look? Mine is still like that old Windows one. I've reinstalled it and it's the same.

**Comment by sw3103** [comment] 2023-09-10 09:57
Ahh - I see now. I flipped mine to dark mode and see the same behaviour.

Move Mouse is written in WPF, which doesn't have a native system tray control. There are a few third-party components out there that offer this, with one of the more popular ones being this which is used in Move Mouse:

https://github.com/hardcodet/wpf-notifyicon

This will explain why it is not conforming to the Windows colour theme changes, and it looks as though the phantom tooltip in the upper right corner is a known issue (as reported on a different project):

https://github.com/canton7/SyncTrayzor/issues/398

There doesn't look like any fix is in sight for this. I think the solution is to either find another third-party control that I can use in its place, or remove the tooltip completely from the next release.

**Comment by dougbenham** [comment] 2023-09-12 06:20
Great job narrowing down the cause! I can confirm I also use dark mode.

Perhaps..
- a config option that disables the tooltip
- or.. detect on startup if dark mode is on and disable the tooltip

**Comment by sw3103** [comment] 2023-09-13 11:43
I am going to explore other options for presenting a system tray icon, otherwise I will simply remove the tooltip from the next release.

**Comment by sw3103** [comment] 2023-11-08 20:49
Removed in [4.17.0](https://github.com/sw3103/movemouse/releases/tag/v4.17.0) release.

**Closed by sw3103** 2023-11-08 20:49 UTC
Labels: help wanted
